"""
Django settings for 试飞风险预警00 project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&b)&74tbs!y3$ryrvcd@33z*cpy4u^xy4uzdo#53zo-6$zl4k8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'FM',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '试飞风险预警00.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '试飞风险预警00.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "staticfiles"),
]
STATIC_ROOT = os.path.join(BASE_DIR, "/static/")
STATIC_URL = '/static/'

# simpleui 配置相关
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
SIMPLEUI_LOGO = "../static/image/AG600.png"
SIMPLEUI_CONFIG = {
    # 是否使用系统默认菜单，自定义菜单时建议关闭。
    'system_keep': False,

    # 用于菜单排序和过滤, 不填此字段为默认排序和全部显示。空列表[] 为全部不显示.
    'menu_display': ['风险基础信息管理', '安全管理', '系统管理'],

    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时刷新展示菜单内容。
    # 一般建议关闭。
    'dynamic': False,
    'menus': [

        {
            'name': '风险基础信息管理',
            'icon': 'fa fa-th-list',
            'models': [
                {
                    'name': '试飞场景管理',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/FM/scenario/',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': '试飞科目管理',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    # 'url': '/admin/FM/subject/',
                    'url': '/database/subjectmanagement/',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': '试飞危险源库管理',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/FM/risksource/',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': '试飞科目危害库管理',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/FM/subjectharm/',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': '危害产生原因分析',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/weixianyuan_by_weihai/',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': '试飞风险知识库管理',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/FM/expertknow/',
                    'icon': 'fa fa-tasks'
                }
            ]
        },
        {
            'app': 'auth',
            'name': '安全管理',
            'icon': 'fas fa-user-shield',
            'models': [
                {
                    'name': '用户列表',
                    'icon': 'fa fa-user',
                    'url': 'auth/user/'
                },
                {
                    'name': '日志管理',
                    'icon': 'fa fa-history',
                    'url': 'admin/logentry/'
                },
            ]
        },

        {
            'app': 'auth',
            'name': '系统管理',
            'icon': 'fa fa-wrench',
            'models': [
                {
                    'name': '配置管理',
                    'icon': 'fa fa-th-list',
                    'url': 'auth/group/'
                },
            ]
        },
    ]
}
