# Generated by Django 4.1.7 on 2023-04-05 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertKnow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('condition', models.CharField(max_length=1024, verbose_name='条件')),
                ('conclusion', models.CharField(max_length=1024, verbose_name='结论')),
            ],
            options={
                'verbose_name': '专家知识库',
                'verbose_name_plural': '专家知识库',
                'db_table': 'ExpertKnow',
            },
        ),
        migrations.CreateModel(
            name='FlyTask',
            fields=[
                ('task_number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='编号')),
                ('tabll', models.CharField(max_length=20, null=True, verbose_name='机型')),
                ('machine_number', models.CharField(max_length=20, null=True, verbose_name='机号')),
                ('edit_time', models.CharField(max_length=20, null=True, verbose_name='编制日期')),
                ('risk_level', models.CharField(max_length=20, null=True, verbose_name='风险科')),
                ('project_name', models.CharField(max_length=20, null=True, verbose_name='课题名称')),
                ('task', models.CharField(max_length=20, null=True, verbose_name='任务单')),
                ('subject', models.CharField(max_length=20, null=True, verbose_name='科目名称')),
                ('distribute_time', models.CharField(max_length=20, null=True, verbose_name='分发日期')),
                ('exe_status', models.CharField(max_length=20, null=True, verbose_name='执行状态')),
                ('creator', models.CharField(max_length=20, null=True, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '试飞任务库',
                'verbose_name_plural': '试飞任务库',
            },
        ),
        migrations.CreateModel(
            name='InitialSubjectHarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=32, verbose_name='科目')),
                ('plane_type', models.CharField(max_length=32, verbose_name='所属机型')),
                ('harm_name', models.CharField(max_length=32, verbose_name='危害名称')),
                ('probability', models.CharField(max_length=32, verbose_name='危害发生可能性')),
                ('seriousness', models.CharField(max_length=32, verbose_name='危害发生严重性')),
                ('risk_level', models.CharField(max_length=32, verbose_name='风险等级')),
                ('reason', models.CharField(max_length=128, verbose_name='危害原因')),
                ('harm_result', models.CharField(max_length=32, verbose_name='危害后果')),
                ('subject_type', models.CharField(max_length=32, verbose_name='风险科目类别')),
                ('measure1', models.CharField(max_length=1024, verbose_name='缓解措施')),
                ('measure2', models.CharField(max_length=1024, verbose_name='应急处置措施')),
                ('left_harm_score', models.CharField(max_length=32, verbose_name='剩余危害评分')),
                ('left_harm_level', models.CharField(max_length=32, verbose_name='剩余危害等级')),
                ('status', models.CharField(max_length=32, verbose_name='提交状态')),
            ],
            options={
                'verbose_name': '初步科目危害库',
                'verbose_name_plural': '初步科目危害库',
                'db_table': 'InitialSubjectHarm',
            },
        ),
        migrations.CreateModel(
            name='RiskSource',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='编号')),
                ('change_time', models.DateField(auto_now=True, verbose_name='入库/修改时间')),
                ('work_stage', models.CharField(max_length=32, verbose_name='工作阶段')),
                ('plane_type', models.CharField(max_length=32, verbose_name='所属机型')),
                ('subject', models.CharField(max_length=32, verbose_name='试飞科目/工作项目')),
                ('risk_source', models.CharField(max_length=32, verbose_name='危险源')),
                ('risk_source_result', models.CharField(max_length=32, verbose_name='危险源后果')),
                ('R_value', models.CharField(max_length=32, verbose_name='风险评分(R值)')),
                ('risk_level', models.CharField(max_length=32, verbose_name='风险等级')),
                ('counter_measures', models.CharField(max_length=1024, verbose_name='缓解/控制措施')),
                ('derive_R_value', models.CharField(max_length=32, verbose_name='衍生风险评分(R值)')),
                ('derive_counter_measures', models.CharField(max_length=1024, verbose_name='衍生风险缓解措施')),
                ('left_risk_level', models.CharField(max_length=32, verbose_name='剩余风险等级')),
                ('approver', models.CharField(max_length=32, verbose_name='风险可接受批准人')),
                ('counter_measures_result', models.CharField(max_length=1024, verbose_name='缓解/控制措施落实情况')),
                ('remarks', models.CharField(max_length=1024, verbose_name='备注')),
            ],
            options={
                'verbose_name': '危险源库',
                'verbose_name_plural': '危险源库',
                'db_table': 'RiskSource',
            },
        ),
        migrations.CreateModel(
            name='RiskSourceActivity',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='编号')),
                ('creator', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('descr', models.CharField(blank=True, max_length=1024, null=True, verbose_name='识别活动描述')),
                ('status', models.CharField(blank=True, max_length=64, null=True, verbose_name='当前识别状态')),
            ],
            options={
                'verbose_name': '危险源识别活动库',
                'verbose_name_plural': '危险源识别活动库',
                'db_table': 'RiskSourceActivity',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=32, verbose_name='场景名称')),
                ('type', models.CharField(max_length=32, verbose_name='场景分类')),
            ],
            options={
                'verbose_name': '场景库',
                'verbose_name_plural': '场景库',
                'db_table': 'Scenario',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='科目编号')),
                ('name', models.CharField(max_length=32, verbose_name='科目名称')),
                ('major', models.CharField(max_length=64, verbose_name='专业')),
                ('type', models.CharField(max_length=32, verbose_name='科目分类')),
            ],
            options={
                'verbose_name': '科目库',
                'verbose_name_plural': '科目库',
            },
        ),
        migrations.CreateModel(
            name='SubjectHarm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('harm_number', models.CharField(max_length=32, verbose_name='危害编号')),
                ('change_time', models.DateField(auto_now=True, verbose_name='入库/修改时间')),
                ('plane_type', models.CharField(max_length=32, verbose_name='所属机型')),
                ('harm_name', models.CharField(max_length=32, verbose_name='危害名称')),
                ('applicable_subject', models.CharField(max_length=32, verbose_name='适用科目')),
                ('R_value', models.CharField(max_length=32, verbose_name='危害评分(R值)')),
                ('harm_level', models.CharField(max_length=32, verbose_name='危害等级')),
                ('subject_type', models.CharField(max_length=32, verbose_name='风险科目类别')),
                ('reason_analysis', models.CharField(max_length=256, verbose_name='原因分析')),
                ('harm_result', models.CharField(max_length=256, verbose_name='危害后果')),
                ('counter_measures', models.CharField(max_length=1024, verbose_name='缓解措施')),
                ('emergency_response_measures', models.CharField(max_length=32, verbose_name='应急处置措施')),
                ('left_R_value', models.CharField(max_length=32, verbose_name='剩余危害评分(R值)')),
                ('left_harm_level', models.CharField(max_length=32, verbose_name='剩余危害等级')),
                ('remarks', models.CharField(max_length=1024, verbose_name='备注')),
            ],
            options={
                'verbose_name': '科目危害库',
                'verbose_name_plural': '科目危害库',
                'db_table': 'SubjectHarm',
            },
        ),
        migrations.CreateModel(
            name='SubjectHarmActivity',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='编号')),
                ('creator', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('descr', models.CharField(blank=True, max_length=1024, null=True, verbose_name='识别活动描述')),
                ('status', models.CharField(blank=True, max_length=64, null=True, verbose_name='当前识别状态')),
            ],
            options={
                'verbose_name': '危害识别活动库',
                'verbose_name_plural': '危害识别活动库',
                'db_table': 'SubjectHarmActivity',
            },
        ),
        migrations.CreateModel(
            name='InitialRiskSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_stage', models.CharField(max_length=32, verbose_name='工作阶段')),
                ('plane_type', models.CharField(max_length=32, verbose_name='所属机型')),
                ('department', models.CharField(max_length=32, verbose_name='所属部门')),
                ('risk_source', models.CharField(max_length=32, verbose_name='危险源')),
                ('risk_source_result', models.CharField(max_length=32, verbose_name='危险源后果')),
                ('reason1', models.CharField(max_length=128, verbose_name='危险原因人的因素')),
                ('reason2', models.CharField(max_length=128, verbose_name='危险原因设备因素')),
                ('reason3', models.CharField(max_length=128, verbose_name='危险原因环境因素')),
                ('reason4', models.CharField(max_length=128, verbose_name='危险原因管理因素')),
                ('R_value', models.CharField(max_length=32, verbose_name='风险评分（R值）')),
                ('risk_level', models.CharField(max_length=32, verbose_name='风险等级')),
                ('counter_measures', models.CharField(max_length=1024, verbose_name='缓解/控制措施')),
                ('question_new1', models.CharField(max_length=32, verbose_name='新问题1')),
                ('question_new2', models.CharField(max_length=32, verbose_name='新问题2')),
                ('probability', models.CharField(max_length=128, verbose_name='危险源发生可能性')),
                ('seriousness', models.CharField(max_length=128, verbose_name='危险源发生严重性')),
                ('left_risk_level', models.CharField(max_length=32, verbose_name='剩余风险等级')),
                ('status', models.CharField(max_length=32, verbose_name='提交状态')),
                ('creator', models.CharField(max_length=20, null=True, verbose_name='创建者')),
                ('fkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FM.risksourceactivity')),
            ],
            options={
                'verbose_name': '初步危险源库',
                'verbose_name_plural': '初步危险源库',
                'db_table': 'InitialRiskSource',
            },
        ),
    ]
