# Generated by Django 4.1.7 on 2023-04-06 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flytask',
            old_name='task_number',
            new_name='id',
        ),
    ]
