# Generated by Django 4.1.7 on 2023-04-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0002_rename_task_number_flytask_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeFlyActivity',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='编号')),
                ('creator', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('descr', models.CharField(blank=True, max_length=1024, null=True, verbose_name='识别活动描述')),
                ('status', models.CharField(blank=True, max_length=64, null=True, verbose_name='当前识别状态')),
            ],
            options={
                'verbose_name': '事前预测活动库',
                'verbose_name_plural': '事前预测活动库',
                'db_table': 'BeforeFlyActivity',
            },
        ),
        migrations.CreateModel(
            name='DuringFlyActivity',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='编号')),
                ('creator', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('descr', models.CharField(blank=True, max_length=1024, null=True, verbose_name='识别活动描述')),
                ('status', models.CharField(blank=True, max_length=64, null=True, verbose_name='当前识别状态')),
            ],
            options={
                'verbose_name': '实时预警活动库',
                'verbose_name_plural': '实时预警活动库',
                'db_table': 'DuringFlyActivity',
            },
        ),
    ]
