# Generated by Django 4.1.2 on 2023-04-06 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0003_beforeflyactivity_duringflyactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskSource_By_SubjectHarm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('risksource_name', models.CharField(max_length=32, verbose_name='危险源名称')),
                ('subjectharm_name', models.CharField(max_length=32, verbose_name='危害名称')),
                ('remarks', models.CharField(max_length=1024, verbose_name='备注')),
                ('risksource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FM.risksource', verbose_name='危险源ID')),
                ('subjectharm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FM.subjectharm', verbose_name='危害ID')),
            ],
            options={
                'verbose_name': '危险源/危害对应关系库',
                'verbose_name_plural': '危险源/危害对应关系库',
                'db_table': 'RiskSource_By_SubjectHarm',
            },
        ),
    ]
