# Generated by Django 4.1.7 on 2023-04-11 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0005_initialrisksource_status_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flytask',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='flytask',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='flytask',
            name='task',
        ),
        migrations.AddField(
            model_name='flytask',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FM.scenario', verbose_name='场景编号'),
        ),
        migrations.AlterField(
            model_name='flytask',
            name='distribute_time',
            field=models.DateField(null=True, verbose_name='分发日期'),
        ),
        migrations.AlterField(
            model_name='flytask',
            name='exe_status',
            field=models.CharField(choices=[('预先准备', '预先准备'), ('直接准备', '直接准备'), ('试飞执行', '试飞执行'), ('飞行后讲评', '飞行后讲评')], max_length=20, null=True, verbose_name='执行状态'),
        ),
        migrations.AlterField(
            model_name='flytask',
            name='subject',
            field=models.CharField(max_length=1000, null=True, verbose_name='试飞科目'),
        ),
    ]
