# Generated by Django 4.1.7 on 2023-04-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0006_remove_flytask_project_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flytask',
            name='distribute_time',
            field=models.DateTimeField(null=True, verbose_name='分发日期'),
        ),
    ]
