# Generated by Django 4.1.7 on 2023-04-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0007_alter_flytask_distribute_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flytask',
            name='scenario',
            field=models.CharField(max_length=1000, null=True, verbose_name='场景'),
        ),
    ]
