# Generated by Django 4.1.7 on 2023-04-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0008_alter_flytask_scenario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flytask',
            name='distribute_time',
        ),
        migrations.RemoveField(
            model_name='flytask',
            name='edit_time',
        ),
    ]
