# Generated by Django 4.1.7 on 2023-04-21 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0009_remove_flytask_distribute_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialsubjectharm',
            name='fkey',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='FM.subjectharmactivity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='risksource',
            name='R_value',
            field=models.CharField(max_length=32, verbose_name='风险评分\n(R值)'),
        ),
        migrations.AlterField(
            model_name='risksource',
            name='derive_R_value',
            field=models.CharField(max_length=32, verbose_name='衍生风险评分\n(R值)'),
        ),
    ]
