# Generated by Django 4.1.2 on 2023-04-21 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0009_remove_flytask_distribute_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialsubjectharm',
            name='fkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FM.subjectharmactivity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectharmactivity',
            name='status_activity',
            field=models.CharField(default='问卷收集中', max_length=20, null=True, verbose_name='当前活动状态'),
        ),
    ]
