# Generated by Django 4.1.7 on 2023-04-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0010_initialsubjectharm_fkey_alter_risksource_r_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risksource',
            name='derive_counter_measures',
            field=models.CharField(max_length=1024, verbose_name='衍生风险\n缓解措施'),
        ),
    ]
