# Generated by Django 4.1.2 on 2023-04-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0010_initialsubjectharm_fkey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialsubjectharm',
            name='creator',
            field=models.CharField(max_length=20, null=True, verbose_name='创建者'),
        ),
    ]
