# Generated by Django 4.1.7 on 2023-04-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0011_alter_risksource_derive_counter_measures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='科目名称'),
        ),
    ]
