# Generated by Django 4.1.2 on 2023-04-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0012_remove_initialsubjectharm_risk_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialsubjectharm',
            name='status_activity',
            field=models.CharField(default='等待审核', max_length=20, null=True, verbose_name='当前问卷状态'),
        ),
    ]
