# Generated by Django 3.2 on 2023-04-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0012_alter_subject_name'),
        ('FM', '0013_initialsubjectharm_status_activity'),
    ]

    operations = [
    ]
