# Generated by Django 3.2 on 2023-04-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0014_merge_20230426_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertknow',
            name='id',
        ),
        migrations.AddField(
            model_name='expertknow',
            name='harm_id',
            field=models.CharField(default=0, max_length=32, verbose_name='危害编号'),
        ),
        migrations.AddField(
            model_name='expertknow',
            name='harm_name',
            field=models.CharField(default=0, max_length=32, verbose_name='危害名称'),
        ),
        migrations.AddField(
            model_name='expertknow',
            name='para_name',
            field=models.CharField(default=0, max_length=1024, verbose_name='参数名称'),
        ),
        migrations.AddField(
            model_name='expertknow',
            name='reference_val',
            field=models.CharField(default=0, max_length=32, verbose_name='参考值'),
        ),
        migrations.AddField(
            model_name='expertknow',
            name='rule_dis',
            field=models.CharField(default=0, max_length=1024, verbose_name='规则描述'),
        ),
        migrations.AddField(
            model_name='expertknow',
            name='rule_id',
            field=models.CharField(default=0, max_length=1024, primary_key=True, serialize=False, verbose_name='编号'),
        ),
        migrations.AddField(
            model_name='expertknow',
            name='stage',
            field=models.CharField(default=0, max_length=1024, verbose_name='阶段'),
        ),
        migrations.AlterField(
            model_name='expertknow',
            name='conclusion',
            field=models.CharField(default=0, max_length=1024, verbose_name='结论'),
        ),
        migrations.AlterField(
            model_name='expertknow',
            name='condition',
            field=models.CharField(default=0, max_length=32, verbose_name='条件'),
        ),
    ]
